### ISSUE TITLE
What difference between offical repo and NerfStudio's repo?

### ISSUE THREAD

**Issue by IceDragonFla** [nerfstudio-project/gsplat#138]
I really love nerfstudio's work and I  first know gsplat is from NerfStudio, and I also try to build my own output model by NerfStudio's youtube videoes.
But as a beginner in DL, I want ask that is there any difference between offical method and your method? like Training logic, hyperparameters or anyother things.

Sry I am not a native English speaker, if there are any offence or other things please tell me. Really want to learn something. =w=

**Comment by maturk** [comment]
Yea there are quite a few differences now. Actually it is difficult to track all the differences since everything has been redone from scratch, so there are differences in the cuda backend and the higher level pytorch code. There are some additional things now as well, that have been incorporated after more papers have come out.

**Comment by IceDragonFla** [comment]
Thank u for answer my issue =w=
looking forword to your new papers =w=
