### ISSUE TITLE
Compile with Debug symbols

### ISSUE THREAD

**Issue by manurare** [nerfstudio-project/gsplat#179]
Hello,

I want to install the cuda extension with debug symbols to debug some additional experiments I am working on.

I am changing [line 76 of setup.py ](https://github.com/nerfstudio-project/gsplat/blob/409bcd3cf63491710444e60c29d3c44608d8eafd/setup.py#L76C5-L76C45) to `nvcc_flags += ["-G"]` but cuda-gdb says that the resulting .so file has no debugging symbols. How could I expose debug symbols?

**Comment by manurare** [comment]
Ok. I had to pip install as follows:

`pip install --no-binary :all: --global-option build --global-option --debug . `

**Comment by ljh12401** [comment]
hello, I wanna ask have you solved this problem by pip install --no-binary :all: --global-option build --global-option --debug . ? I have also been trying to debug gsplat, I added nvcc_flags += ["-g", "-G"] and also tried your command. Unfortunately, none of them worked for me. I used cuda-gdb and "file csrc.so" and it turned out No debugging symbols found in csrc.so
