### ISSUE TITLE
Optical Flow

### ISSUE THREAD

**Issue by ghost** [nerfstudio-project/gsplat#203]
Hi, I'm working on a project where I'm trying to evaluate the temporal consistency of a gsplat model on a video. For this, I'd like to be able to get the optical flow (per pixel) between a pair of images (with a small difference in pose between them). 

My 'idea' is to use the `xys` of both frames to estimate the optical flow from one screen to the other. But Im unsure how to actually implement this, as it would leave a lot of ambiguity (splats closer to the camera move more than splats further away, it does not indicate what splats are actually being rendered, and it does not take into account that splats can occur in mutliple pixels).

I figured I post here in case someone has any suggestions to how to tackle this.

Cheers

**Comment by liruilong940607** [comment]
Hi! In this case what you need is probably the relationship of GS and pixel, i.e. when a GS moves, which pixels are moving. 

We don't return that information in our fully fused  CUDA implementation, but we do provide a function that allows to access that info:

https://github.com/nerfstudio-project/gsplat/blob/07d9188590ae1ee1e9ff7794a4217cc4591b44cf/gsplat/cuda/_torch_impl.py#L444-L446

In fact, after you have that information, the rasterization process (alpha compositing) can be done just on the python side. [`_rasterize_to_pixels`](https://github.com/nerfstudio-project/gsplat/blob/main/gsplat/cuda/_torch_impl.py#L392) shows you how to achieve that. 

Note currently we are only using `_rasterize_to_pixels` to test our fused implementation `rasterize_to_pixels`, which means it is a substitution of the function `rasterize_to_pixels` (but not all arguments are supported). So you can just replace the `rasterize_to_pixels` within the function `rasterization` with  `_rasterize_to_pixels`, and hijack the necessary information you need

**Comment by liruilong940607** [comment]
oh yes it doesn't have to do with GS at all once you render them into an expected depth map.

That being said, there is also another popular way in the NeRF/GS literature, which is to first transform each GS to the next camera coordinate system, then alpha compositing them into a depth map. (the way you have is a switch of these two steps). 

I don't think there is a conclusion in the literature on which way is better, because ideally when training converge perfectly these two give the same outputs. 

Just want to point this out in case it is helpful.
