### ISSUE TITLE
Output rgb out of range

### ISSUE THREAD

**Issue by baoachun** [nerfstudio-project/gsplat#258]
The RGB values output by the rasterization method are not within the [0, 1] range. Should I add a sigmoid function for normalization? The version is 1.0.0.

<img width="905" alt="image" src="https://github.com/nerfstudio-project/gsplat/assets/22114318/2e789d65-7b7e-4de0-b729-48a24ca2df55">

**Comment by liruilong940607** [comment]
Hi you need to apply `sigmoid` to the color before passing it in to the `rasterization()`. We expect the `colors` in the argument to be post-activation values. See
https://github.com/nerfstudio-project/gsplat/blob/2f0bb12f614eb28a5dea2a5422809bc9c388fdb2/examples/simple_trainer.py#L369

But be aware that even if the colors of the GSs (the input of the `rasterization()` function) are normalized to [0, 1], the rendered image could still have values slightly out of the range of [0, 1]. This is caused by the nature of 3DGS formulation. So you would need to clamp to `render_images` to [0, 1] before visualize it or computing metrics on it. See:
https://github.com/nerfstudio-project/gsplat/blob/2f0bb12f614eb28a5dea2a5422809bc9c388fdb2/examples/simple_trainer.py#L846

**Comment by baoachun** [comment]
@liruilong940607 Thank you for your response! After adding the sigmoid function for normalization before the rasterization method, the output still contains values significantly out of range, such as 2.4291. Is this behavior correct?


<img width="905" alt="image" src="https://github.com/nerfstudio-project/gsplat/assets/22114318/138e3e61-576c-409c-b498-4289cec7ab0b">

**Comment by liruilong940607** [comment]
It is reasonable for the beginning of the training.
