### ISSUE TITLE
a bug in transform_cameras()?

### ISSUE THREAD

**Issue by nnop** [nerfstudio-project/gsplat#376]
https://github.com/nerfstudio-project/gsplat/blob/4efec831b0db8276fc91cbb0ae528942ae1c3386/examples/datasets/normalize.py#L128

It seems this should be `camtoworlds[:, :3, 0]` to get x-axis.

**Comment by liruilong940607** [comment]
For just extracting the scaling factor from the matrix, i think both are correct?

**Comment by nnop** [comment]
What's the meaning of `camtoworlds[:, 0, :3]`? 
It seems like x-axis of `world-to-cam` but the scale factor's meaning was not consistent with that.

**Comment by liruilong940607** [comment]
I guess I'm trying to say numerically it does not affect anything because [:3 :3] is a rotation matrix multiples with a scaling factor, so the norm of whatever row/col just equals to this scaling factor.

But I get your point. I agree the [:3, 0] has more intuitive semantic meaning. I'm happy to accept a PR to change it.

**Comment by nnop** [comment]
I'm fine with that, just keep as it is. :)
