### ISSUE TITLE
Detailed Backward Gradient Documentation

### ISSUE THREAD

**Issue by jhonnybhoo** [nerfstudio-project/gsplat#50]
Hello,

Thanks for creating documentation. Are there plans to add derivations for jacobians?

**Comment by vye16** [comment]
Hi, yes we are planning to release detailed derivations soon!

**Comment by jhonnybhoo** [comment]
Thanks. May I know approximately when? A week?

**Comment by vye16** [comment]
Yes we are planning to release within the week.

**Comment by ljjTYJR** [comment]
I would very much appreciate it if you could provide some documents on how to derive proj_mat...
Feel a bit confused about how to set it if I have camera intrinsic parameters.

**Comment by maturk** [comment]
@ljjTYJR for real cams you can try something like this: https://github.com/nerfstudio-project/nerfstudio/blob/40c05be7a60bde25adc28cd281bb9d742c2a77e9/nerfstudio/models/gaussian_splatting.py#L66 this is OpenGL convention using NDC.

**Comment by ljjTYJR** [comment]
> @ljjTYJR for real cams you can try something like this: https://github.com/nerfstudio-project/nerfstudio/blob/40c05be7a60bde25adc28cd281bb9d742c2a77e9/nerfstudio/models/gaussian_splatting.py#L66 this is OpenGL convention using NDC.

Thanks! it helps me.
One minor question: BTW, it seems the coordination used in the `gsplat` and original `Gaussian Splatting`, they do not utilize the OpenGL coordination (with _z_ and _y_ axis are opposite), right?

In addition, for the Projection matrix, why the element at `[2,3]` is 
$-1.0 * f * n / (f - n)$
instead of 
$-2.0 * f * n / (f - n)$
